apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-demo-kv
  namespace: secret-demo
spec:
  provider: azure

  secretObjects:
    - secretName: demo-api-key-k8s
      type: Opaque
      data:
        - objectName: demo-api-key
          key: api-key

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: "a8fd43b8-7bf3-4c4b-abab-c2ac9b20983d"

    keyvaultName: "kv-ilicic-devops-shared"

    objects: |
      array:
        - |
          objectName: demo-api-key
          objectType: secret
          objectVersion: ""

    tenantId: "b2748d0a-856e-4184-bda8-831f9ffa8a48"
