services:
  simple-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-web:local
    container_name: simple-web
    ports:
      - "8080:8080"
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped